// app/layout.tsx
import type { Metadata } from "next";
import { LangProvider } from "@/context/LangContext";
import "./globals.css";
import DockNavWrapper from "@/components/DockNavWrapper";

export const metadata: Metadata = {
  title: "Masoud Jafari",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={`h-full antialiased`} suppressHydrationWarning>
      <head>
        <link
          href="https://cdn.jsdelivr.net/gh/rastikerdar/vazirmatn@v33.003/Vazirmatn-font-face.css"
          rel="stylesheet"
          type="text/css"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:opsz,wght@14..32,100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body 
        className="min-h-full flex flex-col"
        style={{ fontFamily: "Vazirmatn, Inter, sans-serif" }}
      >
        <LangProvider>
          {children}
          <DockNavWrapper />
        </LangProvider>
      </body>
    </html>
  );
}